DROP TABLE TRANSACTIONS_FACT;
DROP TABLE PRODUCT;
DROP TABLE SUPPLIER;
DROP TABLE CUSTOMER;
DROP TABLE STORE;





CREATE TABLE PRODUCT(
PRODUCT_ID VARCHAR2(6), 
PRODUCT_NAME VARCHAR2(30),
PRICE NUMBER(5,2) DEFAULT 0.0,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE SUPPLIER(
SUPPLIER_ID VARCHAR2(5), 
SUPPLIER_NAME VARCHAR2(30) NOT NULL,
CONSTRAINT SUPPLIER_ID_PK PRIMARY KEY(SUPPLIER_ID));

CREATE TABLE CUSTOMER(
CUSTOMER_ID VARCHAR2(4), 
CUSTOMER_NAME VARCHAR2(30) NOT NULL,
CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(CUSTOMER_ID));

CREATE TABLE STORE(
 STORE_ID VARCHAR2(4), 
 STORE_NAME VARCHAR2(20) NOT NULL,
 CONSTRAINT STORE_ID_PK PRIMARY KEY(STORE_ID));
 
 
CREATE TABLE TRANSACTIONS_FACT(
TRANSACTIONS_ID	NUMBER(8,0), 
T_DATE DATE NOT NULL,
QUANTITY NUMBER(3,0) NOT NULL,
PRODUCT_ID VARCHAR2(6) NOT NULL, 
CUSTOMER_ID VARCHAR2(4)	NOT NULL,
SUPPLIER_ID VARCHAR2(5) NOT NULL,
STORE_ID VARCHAR2(4) NOT NULL,
TOTAL_SALE NUMBER(6,2) NOT NULL,
CONSTRAINT TRANSACTIONS_ID_PK PRIMARY KEY(TRANSACTIONS_ID),
CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID), 
CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
CONSTRAINT SUPPLIER_ID_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
CONSTRAINT STORE_ID_FK FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID));

COMMIT;


---------------------
--insert into product
--select product_id,product_name,price
--from  masterdata md;
--
--insert into supplier
--select unique(md.supplier_id),md.supplier_name
--from  masterdata md;
--
--insert into customer
--select unique(t.customer_id),t.customer_name
--from  transactions t,masterdata md;
--
--insert into store
--select unique(t.store_id),t.store_name
--from  transactions t,masterdata md;
--
--insert into transactions_fact
--select t.transactions_id,t.t_date,t.quantity,t.product_id,t.customer_id,md.supplier_id,t.store_id,t.quantity*md.price
--from  transactions t,masterdata md
--where t.product_id=md.product_id;
