DROP TABLE PRODUCT1;
DROP TABLE SUPPLIER1;
DROP TABLE CUSTOMER1;
DROP TABLE STORE1;




CREATE TABLE PRODUCT1(
PRODUCT_ID VARCHAR2(6), 
PRODUCT_NAME VARCHAR2(30),
PRICE NUMBER(5,2) DEFAULT 0.0,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE SUPPLIER1(
SUPPLIER_ID VARCHAR2(5), 
SUPPLIER_NAME VARCHAR2(30) NOT NULL,
CONSTRAINT SUPPLIER_ID_PK PRIMARY KEY(SUPPLIER_ID));

CREATE TABLE CUSTOMER1(
CUSTOMER_ID VARCHAR2(4), 
CUSTOMER_NAME VARCHAR2(30) NOT NULL,
CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(CUSTOMER_ID));

CREATE TABLE STORE1(
 STORE_ID VARCHAR2(4), 
 STORE_NAME VARCHAR2(20) NOT NULL,
 CONSTRAINT STORE_ID_PK PRIMARY KEY(STORE_ID));
 
 COMMIT;
 
 CREATE TABLE TRANSACTIONS_FACT(
TRANSACTIONS_ID	NUMBER(8,0), 
T_DATE DATE NOT NULL,
QUANTITY NUMBER(3,0) NOT NULL,
PRODUCT_ID VARCHAR2(6) NOT NULL, 
CUSTOMER_ID VARCHAR2(4)	NOT NULL,
SUPPLIER_ID VARCHAR2(5) NOT NULL,
STORE_ID VARCHAR2(4) NOT NULL,
TOTAL_SALE NUMBER(6,2) NOT NULL,
CONSTRAINT TRAINSACTION_ID_PK PRIMARY KEY(TRASACTION_ID),
CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT1(PRODUCT_ID), 
CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER1(CUSTOMER_ID),
CONSTRAINT SUPPLIER_ID_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER1(SUPPLIER_ID),
CONSTRAINT STORE_ID_FK FOREIGN KEY (STORE_ID) REFERENCES STORE1(STORE_ID));